In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('cropdata19972017.xlsx')

In [3]:
df.head(10)

,DISTNAME,YEAR,CROP,SEASON,AREA(HECTARE),PRODUCTION(TONNES),YIELD(TONNES/HECTARE)
0,ADILABAD,1997,Arhar/Tur,Kharif,32200.0,1100.0,0.034161
1,ANANTAPUR,1997,Arhar/Tur,Kharif,21400.0,2600.0,0.121495
2,CHITTOOR,1997,Arhar/Tur,Kharif,6100.0,900.0,0.147541
3,EAST GODAVARI,1997,Arhar/Tur,Kharif,1600.0,300.0,0.187500
4,GUNTUR,1997,Arhar/Tur,Kharif,28400.0,14900.0,0.524648
5,Y.S.R. Kadapa,1997,Arhar/Tur,Kharif,5700.0,1400.0,0.245614
6,KARIMNAGAR,1997,Arhar/Tur,Kharif,3100.0,400.0,0.129032
7,KHAMMAM,1997,Arhar/Tur,Kharif,25400.0,8400.0,0.330709
8,KRISHNA,1997,Arhar/Tur,Kharif,10700.0,3400.0,0.317757
9,KURNOOL,1997,Arhar/Tur,Kharif,20900.0,6400.0,0.306220

In [36]:
#yearwisedf = pd.DataFrame()
yearwisedf = pd.DataFrame(index=range(800))

def processing(df):
    for year in range(1997, 2017):
        yearwisedistricts = df[df.YEAR == year]['DISTNAME'].unique()
        yearwisedf[year] = pd.Series(yearwisedistricts)

In [37]:
processing(df)

In [38]:
yearwisedf.head(10)

,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,ADILABAD,ADILABAD,ADILABAD,NICOBARS,NICOBARS,NICOBARS,NICOBARS,NICOBARS,NICOBARS,NORTH AND MIDDLE ANDAMAN,NaN,ADILABAD,ADILABAD,NICOBARS,NICOBARS,NICOBARS,NICOBARS,NICOBARS,NICOBARS,NICOBARS
1,ANANTAPUR,ANANTAPUR,ANANTAPUR,NORTH AND MIDDLE ANDAMAN,NORTH AND MIDDLE ANDAMAN,SOUTH ANDAMANS,SOUTH ANDAMANS,SOUTH ANDAMANS,SOUTH ANDAMANS,SOUTH ANDAMANS,ADILABAD,ANANTAPUR,ANANTAPUR,NORTH AND MIDDLE ANDAMAN,NORTH AND MIDDLE ANDAMAN,NORTH AND MIDDLE ANDAMAN,NORTH AND MIDDLE ANDAMAN,NORTH AND MIDDLE ANDAMAN,NORTH AND MIDDLE ANDAMAN,NORTH AND MIDDLE ANDAMAN
2,CHITTOOR,CHITTOOR,CHITTOOR,ADILABAD,ADILABAD,ADILABAD,ADILABAD,ADILABAD,ADILABAD,ADILABAD,ANANTAPUR,CHITTOOR,CHITTOOR,SOUTH ANDAMANS,SOUTH ANDAMANS,SOUTH ANDAMANS,SOUTH ANDAMANS,SOUTH ANDAMANS,SOUTH ANDAMANS,SOUTH ANDAMANS
3,EAST GODAVARI,EAST GODAVARI,EAST GODAVARI,ANANTAPUR,ANANTAPUR,ANANTAPUR,ANANTAPUR,ANANTAPUR,ANANTAPUR,ANANTAPUR,CHITTOOR,EAST GODAVARI,EAST GODAVARI,ADILABAD,ADILABAD,ANANTAPUR,ANANTAPUR,ANANTAPUR,ANANTAPUR,ANANTAPUR
4,GUNTUR,GUNTUR,GUNTUR,CHITTOOR,CHITTOOR,CHITTOOR,CHITTOOR,CHITTOOR,CHITTOOR,CHITTOOR,EAST GODAVARI,GUNTUR,GUNTUR,ANANTAPUR,ANANTAPUR,EAST GODAVARI,EAST GODAVARI,EAST GODAVARI,EAST GODAVARI,EAST GODAVARI
5,Y.S.R. Kadapa,Y.S.R. Kadapa,Y.S.R. Kadapa,EAST GODAVARI,EAST GODAVARI,EAST GODAVARI,EAST GODAVARI,EAST GODAVARI,EAST GODAVARI,EAST GODAVARI,GUNTUR,Y.S.R. Kadapa,Y.S.R. Kadapa,CHITTOOR,CHITTOOR,VIZIANAGARAM,CHITTOOR,CHITTOOR,CHITTOOR,VIZIANAGARAM
6,KARIMNAGAR,KARIMNAGAR,KARIMNAGAR,GUNTUR,GUNTUR,GUNTUR,GUNTUR,GUNTUR,GUNTUR,GUNTUR,Y.S.R. Kadapa,KARIMNAGAR,KARIMNAGAR,EAST GODAVARI,EAST GODAVARI,ADILABAD,GUNTUR,GUNTUR,GUNTUR,WEST GODAVARI
7,KHAMMAM,KHAMMAM,KHAMMAM,Y.S.R. Kadapa,Y.S.R. Kadapa,Y.S.R. Kadapa,Y.S.R. Kadapa,Y.S.R. Kadapa,Y.S.R. Kadapa,Y.S.R. Kadapa,KARIMNAGAR,KHAMMAM,KHAMMAM,GUNTUR,GUNTUR,CHITTOOR,Y.S.R. Kadapa,Y.S.R. Kadapa,Y.S.R. Kadapa,CHITTOOR
8,KRISHNA,KRISHNA,KURNOOL,KARIMNAGAR,KARIMNAGAR,KARIMNAGAR,KARIMNAGAR,KARIMNAGAR,KARIMNAGAR,KARIMNAGAR,KHAMMAM,KRISHNA,KRISHNA,Y.S.R. Kadapa,Y.S.R. Kadapa,GUNTUR,KRISHNA,KRISHNA,KRISHNA,GUNTUR
9,KURNOOL,KURNOOL,MAHBUBNAGAR,KHAMMAM,KHAMMAM,KHAMMAM,KHAMMAM,KHAMMAM,KHAMMAM,KHAMMAM,KRISHNA,KURNOOL,KURNOOL,KARIMNAGAR,KARIMNAGAR,Y.S.R. Kadapa,KURNOOL,KURNOOL,KURNOOL,Y.S.R. Kadapa

In [39]:
yearwisedf.tail(10)

,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
yearwisedf.to_excel('yearwisedistricts.xlsx', index = None)